/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UjianTengahSemester;

import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author WINDOWS 10
 */
public class SyPulsa extends JFrame {

    /**
     * Creates new form SyPulsa
     */
    public SyPulsa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelutama = new javax.swing.JPanel();
        panellogo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelmenu = new javax.swing.JPanel();
        paneltutup = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblnomor = new javax.swing.JLabel();
        lbloperator = new javax.swing.JLabel();
        lbllayanan = new javax.swing.JLabel();
        lblnominal = new javax.swing.JLabel();
        lblharga = new javax.swing.JLabel();
        btnbayar = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        txharga = new javax.swing.JTextField();
        txnominal = new javax.swing.JTextField();
        cmblayanan = new javax.swing.JComboBox<>();
        cmboperator = new javax.swing.JComboBox<>();
        txnmrtlpn = new javax.swing.JTextField();
        btnlogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txpassword = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txusername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelutama.setBackground(new java.awt.Color(0, 153, 102));
        panelutama.setMinimumSize(new java.awt.Dimension(581, 402));
        panelutama.setPreferredSize(new java.awt.Dimension(590, 402));
        panelutama.setRequestFocusEnabled(false);
        panelutama.setVerifyInputWhenFocusTarget(false);
        panelutama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panellogo.setBackground(new java.awt.Color(0, 102, 51));
        panellogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 55)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SyPulsa");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINDOWS 10\\Pictures\\logosphitam-fiks2.png")); // NOI18N
        jLabel8.setText("jLabel1");

        javax.swing.GroupLayout panellogoLayout = new javax.swing.GroupLayout(panellogo);
        panellogo.setLayout(panellogoLayout);
        panellogoLayout.setHorizontalGroup(
            panellogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellogoLayout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        panellogoLayout.setVerticalGroup(
            panellogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellogoLayout.createSequentialGroup()
                .addGroup(panellogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panellogoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panellogoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelutama.add(panellogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelmenu.setBackground(new java.awt.Color(0, 153, 153));
        panelmenu.setMaximumSize(new java.awt.Dimension(276, 176));
        panelmenu.setPreferredSize(new java.awt.Dimension(100, 200));
        panelmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneltutup.setBackground(new java.awt.Color(0, 153, 153));
        paneltutup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DATANG");
        paneltutup.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 210, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UjianTengahSemester/WhatsApp_Image_2024-12-17_at_00.50.17-removebg-preview.png"))); // NOI18N
        paneltutup.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 280, 260));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SELAMAT");
        paneltutup.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UjianTengahSemester/wa-removebg-preview.png"))); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(80, 40));
        paneltutup.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UjianTengahSemester/ige2.png"))); // NOI18N
        paneltutup.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 40, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("noviwull_");
        paneltutup.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 100, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("081288865297");
        paneltutup.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 100, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Novi Wulandari");
        paneltutup.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 100, -1));

        panelmenu.add(paneltutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 350, 290));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" ");
        panelmenu.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 70, 84, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MENU LAYANAN");
        panelmenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 35));

        lblnomor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnomor.setForeground(new java.awt.Color(255, 255, 255));
        lblnomor.setText("NOMOR TELEPON");
        panelmenu.add(lblnomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 111, 25));

        lbloperator.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbloperator.setForeground(new java.awt.Color(255, 255, 255));
        lbloperator.setText("JENIS OPERATOR");
        panelmenu.add(lbloperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 111, 25));

        lbllayanan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbllayanan.setForeground(new java.awt.Color(255, 255, 255));
        lbllayanan.setText("JENIS LAYANAN");
        panelmenu.add(lbllayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 111, 25));

        lblnominal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnominal.setForeground(new java.awt.Color(255, 255, 255));
        lblnominal.setText("NOMINAL");
        panelmenu.add(lblnominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 111, 25));

        lblharga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblharga.setForeground(new java.awt.Color(255, 255, 255));
        lblharga.setText("HARGA");
        panelmenu.add(lblharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 111, 25));

        btnbayar.setBackground(new java.awt.Color(153, 153, 153));
        btnbayar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnbayar.setForeground(new java.awt.Color(255, 255, 255));
        btnbayar.setText("BAYAR");
        btnbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbayarActionPerformed(evt);
            }
        });
        panelmenu.add(btnbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        btnlogout.setBackground(new java.awt.Color(153, 153, 153));
        btnlogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("LOGOUT");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        panelmenu.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        txharga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txhargaActionPerformed(evt);
            }
        });
        panelmenu.add(txharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 159, -1));

        txnominal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txnominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnominalActionPerformed(evt);
            }
        });
        panelmenu.add(txnominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 159, -1));

        cmblayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH LAYANAN", "PULSA", "PAKET", " ", " " }));
        cmblayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmblayananActionPerformed(evt);
            }
        });
        panelmenu.add(cmblayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 159, -1));

        cmboperator.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH OPERATOR", "XL", "TELKOMSEL", "SMARTFREN", "AXIS" }));
        cmboperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboperatorActionPerformed(evt);
            }
        });
        panelmenu.add(cmboperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 159, 25));

        txnmrtlpn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txnmrtlpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnmrtlpnActionPerformed(evt);
            }
        });
        panelmenu.add(txnmrtlpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 159, -1));

        panelutama.add(panelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 120, 350, 280));

        btnlogin.setBackground(new java.awt.Color(0, 153, 153));
        btnlogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("LOGIN");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        panelutama.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD");
        panelutama.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 84, 25));

        txpassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelutama.add(txpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 125, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("USERNAME");
        panelutama.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 84, 25));

        txusername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txusernameActionPerformed(evt);
            }
        });
        panelutama.add(txusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 125, 23));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LOGIN");
        panelutama.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 35));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Masukkan Username & Password");
        panelutama.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 215, -1));

        getContentPane().add(panelutama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
           
        String username = txusername.getText();
        
        String password = new String(txpassword.getText());
        
        if (username.equals("admin") && password.equals("123"))
        {panelmenu.setVisible(true);
         paneltutup.setVisible(false);
        JOptionPane.showMessageDialog(null, "LOGIN BERHASIL!");}
        
        else
        {JOptionPane.showMessageDialog(null, "USERNAME ATAU PASSWORD SALAH !");}

    }//GEN-LAST:event_btnloginActionPerformed

    private void btnbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbayarActionPerformed
        // TODO add your handling code here:
        String nomorTelepon = txnmrtlpn.getText();
        String operator = (String) cmboperator.getSelectedItem();
        String layanan = (String) cmblayanan.getSelectedItem();
        String nominalStr = txnominal.getText();
        int nominal = Integer.parseInt(nominalStr);
        String hargaStr = txharga.getText();
       
        
        // Validasi input
        if (!nomorTelepon.matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "Nomor telepon harus berupa angka!");
        return;}
        
        if (nominal <= 0) {
        JOptionPane.showMessageDialog(null, "Nominal harus lebih dari 0!");
        return;
}
        //Hitung harga
        int harga = nominal + 5000;
        
        //tampilkan pesan konfirmasi
        JOptionPane.showMessageDialog
        (null, "Pembayaran berhasil!\nNomor: " + nomorTelepon + 
                "\nOperator: " + operator + 
                "\nNominal: " + nominal + 
                "\nHarga: Rp " + harga);
    }//GEN-LAST:event_btnbayarActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog
        (null, "Apakah Anda yakin ingin logout?", 
                "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);
                if (pilihan == JOptionPane.YES_OPTION) {
                    // Kembali ke halaman login atau halaman utama
                    dispose(); // Tutup jendela saat ini
                }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void txusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txusernameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txusernameActionPerformed

    private void txnmrtlpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnmrtlpnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnmrtlpnActionPerformed

    private void cmblayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmblayananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmblayananActionPerformed

    private void txhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txhargaActionPerformed

    private void cmboperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboperatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboperatorActionPerformed

    private void txnominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnominalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnominalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SyPulsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SyPulsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SyPulsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SyPulsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SyPulsa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbayar;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnlogout;
    private javax.swing.JComboBox<String> cmblayanan;
    private javax.swing.JComboBox<String> cmboperator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblharga;
    private javax.swing.JLabel lbllayanan;
    private javax.swing.JLabel lblnominal;
    private javax.swing.JLabel lblnomor;
    private javax.swing.JLabel lbloperator;
    private javax.swing.JPanel panellogo;
    private javax.swing.JPanel panelmenu;
    private javax.swing.JPanel paneltutup;
    private javax.swing.JPanel panelutama;
    private javax.swing.JTextField txharga;
    private javax.swing.JTextField txnmrtlpn;
    private javax.swing.JTextField txnominal;
    private javax.swing.JTextField txpassword;
    private javax.swing.JTextField txusername;
    // End of variables declaration//GEN-END:variables
}
