/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas;

import backupsypulsa.*;
import uas.*;
import java.sql.Statement;
//import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author WINDOWS 10
 */
public class DataSYpulsa extends javax.swing.JFrame {

    /**
     * Creates new form DataSYpulsa
     */
    public DataSYpulsa() {
   
         //MEMANGGIL KELAS
        initComponents();
        this.setLocationRelativeTo(this);
        this.setTitle("Aplikasi Data SYPULSA");
        
        koneksiuas k = new koneksiuas();
        //query q = new query();
        
        k.RunKoneksi();
        txstatus.setText(k.statuskoneksi);
        
        ButtonGroup bG = new ButtonGroup ();
        bG.add (rdpulsa);
        bG.add (rdpaket);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //UNTUK KLIK MOUSE
    Statement pst ;
    ResultSet rs;
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlutama = new javax.swing.JPanel();
        pnllogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblsypulsa = new javax.swing.JLabel();
        lblsypulsa1 = new javax.swing.JLabel();
        lbllayanan = new javax.swing.JLabel();
        txharga = new javax.swing.JTextField();
        lblnomor = new javax.swing.JLabel();
        txnomor = new javax.swing.JTextField();
        lblharga = new javax.swing.JLabel();
        rdpaket = new javax.swing.JRadioButton();
        rdpulsa = new javax.swing.JRadioButton();
        lbloperator = new javax.swing.JLabel();
        txoperator = new javax.swing.JTextField();
        lblnominal1 = new javax.swing.JLabel();
        txnominal = new javax.swing.JTextField();
        pntabel = new javax.swing.JPanel();
        lbldataisi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblisi = new javax.swing.JTable();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnselect = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnstatus = new javax.swing.JButton();
        btnbayar = new javax.swing.JButton();
        txstatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlutama.setBackground(new java.awt.Color(0, 102, 102));
        pnlutama.setAutoscrolls(true);
        pnlutama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnllogo.setBackground(new java.awt.Color(0, 153, 102));
        pnllogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        pnllogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/lgspfik.png"))); // NOI18N
        pnllogo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 60));

        lblsypulsa.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        lblsypulsa.setForeground(new java.awt.Color(255, 255, 255));
        lblsypulsa.setText("Cepat, Mudah, Terpercaya");
        pnllogo.add(lblsypulsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, -1));

        lblsypulsa1.setFont(new java.awt.Font("Impact", 1, 60)); // NOI18N
        lblsypulsa1.setForeground(new java.awt.Color(255, 255, 255));
        lblsypulsa1.setText("SYPULSAMU");
        pnllogo.add(lblsypulsa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 330, 50));

        pnlutama.add(pnllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 80));

        lbllayanan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbllayanan.setForeground(new java.awt.Color(255, 255, 255));
        lbllayanan.setText("JENIS LAYANAN");
        pnlutama.add(lbllayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 20));

        txharga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnlutama.add(txharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 130, -1));

        lblnomor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnomor.setForeground(new java.awt.Color(255, 255, 255));
        lblnomor.setText("MASUKKAN NOMOR");
        pnlutama.add(lblnomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 20));

        txnomor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnlutama.add(txnomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, -1));

        lblharga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblharga.setForeground(new java.awt.Color(255, 255, 255));
        lblharga.setText("TOTAL HARGA");
        pnlutama.add(lblharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 130, 20));

        rdpaket.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdpaket.setForeground(new java.awt.Color(255, 255, 255));
        rdpaket.setText("PAKET");
        rdpaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdpaketActionPerformed(evt);
            }
        });
        pnlutama.add(rdpaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        rdpulsa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdpulsa.setForeground(new java.awt.Color(255, 255, 255));
        rdpulsa.setText("PULSA");
        rdpulsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdpulsaActionPerformed(evt);
            }
        });
        pnlutama.add(rdpulsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        lbloperator.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbloperator.setForeground(new java.awt.Color(255, 255, 255));
        lbloperator.setText("JENIS OPERATOR");
        pnlutama.add(lbloperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 20));

        txoperator.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnlutama.add(txoperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, -1));

        lblnominal1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnominal1.setForeground(new java.awt.Color(255, 255, 255));
        lblnominal1.setText("MASUKKAN NOMINAL");
        pnlutama.add(lblnominal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 130, 20));

        txnominal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnlutama.add(txnominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, -1));

        pntabel.setBackground(new java.awt.Color(0, 204, 153));
        pntabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        pntabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbldataisi.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lbldataisi.setForeground(new java.awt.Color(255, 255, 255));
        lbldataisi.setText("DATA ISI");
        pntabel.add(lbldataisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 30));

        tblisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NOMOR", "OPERATOR", "NOMINAL", "HARGA", "LAYANAN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblisiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblisi);

        pntabel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 330, 210));

        btnedit.setBackground(new java.awt.Color(0, 153, 153));
        btnedit.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        pntabel.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 70, 30));

        btndelete.setBackground(new java.awt.Color(0, 153, 153));
        btndelete.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        pntabel.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, 30));

        btnselect.setBackground(new java.awt.Color(0, 153, 153));
        btnselect.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnselect.setForeground(new java.awt.Color(255, 255, 255));
        btnselect.setText("SELECT");
        btnselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselectActionPerformed(evt);
            }
        });
        pntabel.add(btnselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 90, 30));

        btnreset.setBackground(new java.awt.Color(0, 153, 153));
        btnreset.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnreset.setForeground(new java.awt.Color(255, 255, 255));
        btnreset.setText("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        pntabel.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 80, 30));

        pnlutama.add(pntabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 350, 290));

        btnstatus.setBackground(new java.awt.Color(0, 153, 153));
        btnstatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnstatus.setForeground(new java.awt.Color(255, 255, 255));
        btnstatus.setText("STATUS");
        btnstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstatusActionPerformed(evt);
            }
        });
        pnlutama.add(btnstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 100, 30));

        btnbayar.setBackground(new java.awt.Color(0, 153, 153));
        btnbayar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnbayar.setForeground(new java.awt.Color(255, 255, 255));
        btnbayar.setText("BAYAR");
        btnbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbayarActionPerformed(evt);
            }
        });
        pnlutama.add(btnbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 110, 30));

        txstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txstatusActionPerformed(evt);
            }
        });
        pnlutama.add(txstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 230, 30));

        getContentPane().add(pnlutama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdpaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdpaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdpaketActionPerformed

    private void rdpulsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdpulsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdpulsaActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
    // TODO add your handling code here:
    koneksiuas konek = new koneksiuas();
        konek.RunKoneksi();
        
        queryupdate ubah  = new queryupdate();
        String NOMOR = txnomor.getText();
        String OPERATOR = txoperator.getText();
        String NOMINAL = txnominal.getText();
        int NOMINALValue = Integer.parseInt(NOMINAL);
        int HARGAValue = NOMINALValue + 2000;
        txharga.setText(String.valueOf(HARGAValue));
        String HARGA = String .valueOf(HARGAValue);
        
        String LAYANAN = "";
        
            if (rdpulsa.isSelected())
            {LAYANAN = "PL";}
            else if (rdpaket.isSelected())
            {LAYANAN = "PK";}
            
            ubah.updateData(NOMOR, OPERATOR, NOMINAL, HARGA, LAYANAN);
        //MENAMPILKAN UPDATE KE TABEL ISI
        queryselect qs = new queryselect();
        qs.select(tblisi); // Melewatkan tabel tblisi ke method select
    }//GEN-LAST:event_btneditActionPerformed

    private void btnstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnstatusActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        koneksiuas konek = new koneksiuas();  
        konek.RunKoneksi();
        
        querydelete delete = new querydelete ();
        delete.hapus(txnomor.getText());
        //MENAMPILKAN UPDATE KE TABEL ISI
        queryselect qs = new queryselect();
        qs.select(tblisi); // Melewatkan tabel tblisi ke method select

       
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselectActionPerformed
        // TODO add your handling code here:
        queryselect qs = new queryselect();
        qs.select(tblisi); // Melewatkan tabel tblisi ke method select
        
    }//GEN-LAST:event_btnselectActionPerformed

    private void btnbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbayarActionPerformed
        // TODO add your handling code here:
        String LAYANAN =  "";
        if (rdpulsa.isSelected())
        {LAYANAN = "PL";}
        else if (rdpaket.isSelected())
        {LAYANAN = "PK";}
        
        //membuat class baru dari query insert
        queryinsert in = new queryinsert ();
        
        String NOMOR = txnomor.getText();
        String OPERATOR = txoperator.getText();
        String NOMINAL = txnominal.getText();
        int NOMINALValue = Integer.parseInt(NOMINAL);
        int HARGAValue = NOMINALValue + 2000;
        txharga.setText(String.valueOf(HARGAValue));
      
        //String HARGA = txharga.getText();
        //int NOMINAL = Integer.parseInt(txnominal.getText());
        //int HARGA = NOMINAL + 2000;
        String HARGA = String .valueOf(HARGAValue);
        
        in.insert(NOMOR, OPERATOR, NOMINAL, HARGA, LAYANAN);
        //MENAMPILKAN INSERT KE TABEL ISI
        queryselect qs = new queryselect();
        qs.select(tblisi); // Melewatkan tabel tblisi ke method select
        
        
    }//GEN-LAST:event_btnbayarActionPerformed

    private void txstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txstatusActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        txnomor.setText("");
        txoperator.setText("");
        txnominal.setText("");
        txharga.setText("");
        ButtonGroup bG = new ButtonGroup ();
        bG.add (rdpulsa);
        bG.add (rdpaket);
        bG.clearSelection();
        
    }//GEN-LAST:event_btnresetActionPerformed

    private void tblisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblisiMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel dtm = ( DefaultTableModel) tblisi.getModel();
        int selectedrowindex = tblisi.getSelectedRow();
        String id = (String) dtm.getValueAt(selectedrowindex , 0);
        
         koneksiuas konek = new koneksiuas();
         konek.RunKoneksi();
        
         try {
            String sql = "select * from `isi` where nomor like '%" + id + "%'";
            Statement pst  = konek.conn.createStatement();
            pst = (Statement) konek.conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            
            while (rs.next())
            {txnomor.setText(rs.getString("NOMOR"));
            txoperator.setText(rs.getString("OPERATOR"));
            txnominal.setText(rs.getString("NOMINAL"));
            txharga.setText(rs.getString("HARGA"));
            
            String layanan = rs.getString("LAYANAN");
            if(layanan.equals("PL"))
            {rdpulsa.setSelected(true);}
            else
            {rdpaket.setSelected(true);}
            
            
            }
             
         }
catch(Exception ex){}


    }//GEN-LAST:event_tblisiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataSYpulsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataSYpulsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataSYpulsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataSYpulsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataSYpulsa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbayar;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnselect;
    private javax.swing.JButton btnstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldataisi;
    private javax.swing.JLabel lblharga;
    private javax.swing.JLabel lbllayanan;
    private javax.swing.JLabel lblnominal1;
    private javax.swing.JLabel lblnomor;
    private javax.swing.JLabel lbloperator;
    private javax.swing.JLabel lblsypulsa;
    private javax.swing.JLabel lblsypulsa1;
    private javax.swing.JPanel pnllogo;
    private javax.swing.JPanel pnlutama;
    private javax.swing.JPanel pntabel;
    private javax.swing.JRadioButton rdpaket;
    private javax.swing.JRadioButton rdpulsa;
    private javax.swing.JTable tblisi;
    private javax.swing.JTextField txharga;
    private javax.swing.JTextField txnominal;
    private javax.swing.JTextField txnomor;
    private javax.swing.JTextField txoperator;
    private javax.swing.JTextField txstatus;
    // End of variables declaration//GEN-END:variables
}
