/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas_pertemuan5;

import javax.swing.JOptionPane;

/**
 *
 * @author WINDOWS 10
 */
public class Aurora_Beauty extends javax.swing.JFrame {

    /**
     * Creates new form Aurora_Beauty
     */
    public Aurora_Beauty() {
        initComponents();
    }
    
    public int Total_Harga;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combo_jenis = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_ukuran = new javax.swing.JTextField();
        txt_ttlharga = new javax.swing.JTextField();
        txt_bayar = new javax.swing.JTextField();
        btn_batal = new javax.swing.JButton();
        btn_transaksi = new javax.swing.JButton();
        txt_harga = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AURORA BEAUTY ");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 220, 20));

        jLabel2.setText("BAYAR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, 30));

        combo_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH PERAWATAN", "HAIR CUT", "CREAMBATH", "HAIR COLORING", "SMOOTHING", " " }));
        combo_jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_jenisActionPerformed(evt);
            }
        });
        jPanel1.add(combo_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 140, 30));

        jLabel3.setText("JENIS PERAWATAN ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 30));

        jLabel4.setText("UKURAN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, 30));

        jLabel5.setText("HARGA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, 30));

        jLabel6.setText("TOTAL HARGA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 30));

        txt_ukuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ukuranActionPerformed(evt);
            }
        });
        txt_ukuran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_ukuranKeyReleased(evt);
            }
        });
        jPanel1.add(txt_ukuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 140, 30));

        txt_ttlharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ttlhargaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_ttlharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 140, 30));

        txt_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bayarActionPerformed(evt);
            }
        });
        jPanel1.add(txt_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 140, 30));

        btn_batal.setText("BATAL");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 100, 40));

        btn_transaksi.setText("TRANSAKSI");
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 100, 40));

        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });
        txt_harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_hargaKeyReleased(evt);
            }
        });
        jPanel1.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 140, 30));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 550, 430);

        setSize(new java.awt.Dimension(510, 423));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combo_jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_jenisActionPerformed
        // TODO add your handling code here:
        
        if (combo_jenis.getSelectedItem().equals("Pilih Perawatan"))
        {txt_harga.setText("0");}
        else if(combo_jenis.getSelectedItem().equals("HAIR CUT"))
        {txt_harga.setText("10000");}
        else if(combo_jenis.getSelectedItem().equals("CREAMBATH"))
        {txt_harga.setText("10000");}
        else if(combo_jenis.getSelectedItem().equals("HAIR COLORING"))
        {txt_harga.setText("50000");}
        else if(combo_jenis.getSelectedItem().equals("SMOOTHING"))
        {txt_harga.setText("200000");}
        
        
    }//GEN-LAST:event_combo_jenisActionPerformed

    private void txt_ukuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ukuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ukuranActionPerformed

    private void txt_ttlhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ttlhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ttlhargaActionPerformed

    private void txt_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bayarActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        dispose ();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        // TODO add your handling code here:
    if (txt_harga.getText().isEmpty() || txt_ukuran.getText().isEmpty() || txt_ttlharga.getText().isEmpty() || txt_bayar.getText().isEmpty())
    {JOptionPane.showMessageDialog (null, "Data Harus Diisi Lengkap");}
        
    else {
        int bayar = Integer.parseInt(txt_bayar.getText());
        int kembalian = bayar-Total_Harga;
        JOptionPane.showMessageDialog(null, "Kembalian Anda :\n"+kembalian);
    }
    }//GEN-LAST:event_btn_transaksiActionPerformed

    private void txt_ukuranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ukuranKeyReleased
        // TODO add your handling code here:
        if (txt_ukuran.getText().equals(""))
        {txt_ttlharga.setText("0");}
        
        else{
            int harga = Integer.parseInt(txt_harga.getText());
            int ukuran = Integer.parseInt(txt_ukuran.getText());
            Total_Harga = harga*ukuran;
            txt_ttlharga.setText(String.valueOf(Total_Harga));
        }
    }//GEN-LAST:event_txt_ukuranKeyReleased

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void txt_hargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hargaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aurora_Beauty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aurora_Beauty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aurora_Beauty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aurora_Beauty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aurora_Beauty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JComboBox<String> combo_jenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_ttlharga;
    private javax.swing.JTextField txt_ukuran;
    // End of variables declaration//GEN-END:variables
}
